config/routes.rb
Rails.application.routes.draw do

 devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
  get "/" => "homes#top"
  resources :genres, only: [:index, :edit, :create, :update]
  get "/search" => "posts#search"
  get "/users/unsubscribe" => "users#unsubscribe"
  patch "/users/is_deleted" => "users#is_deleted"
  resources :posts, only: [:index, :create, :new, :show, :edit, :update]
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
    get :likes

  end

  end


 end

scope module: :public do
  root "homes#top"
  get "/about" => "homes#about"
  get "/users/unsubscribe" => "users#unsubscribe"
  patch "/users/is_deleted" => "users#is_deleted"
  resources :users,only: [:index, :create, :new, :show, :edit, :update, :destroy] do
    member do
    get :likes
   end
  end
  resources :posts,only: [:new,:create,:index,:show,:destroy,:edit,:update] do
   resource :likes, only: [:create, :destroy]
   resources :comments, only: [:create, :destroy]
   get 'search'
   end
  get 'keyword_search' => "posts#keyword_search"
  get "/search" => "posts#search"

 end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

with_options presence: true, on: :publicize do
  validates :title
  validates :body
  validates :genre_id

end
validates :title, length: { maximum: 30 }, on: :publicize
validates :body, length: { maximum: 500 }, on: :publicize


  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

  def get_image(width, height)
   unless image.attached?
     file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
     image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def new
    @post=Post.new
    @user=@post.user
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = user.id

    if @post.save
      flash[:notice] = "You have created post successfully."
      redirect_to post_path(@post.id)
    else
      @posts=Post.all
      render :index
    end
  end

  def show
    @post=Post.find(params[:id])
    @user=@post.user
    @comment = Comment.new
  end

  def edit
    @user=User.find(params[:id])
    @post=Post.find(params[:id])

      render "edit"

  end

  def search
    @posts = Post.page(params[:page]).per(10)
    @word_for_search = Genre.find(params[:word_for_search])
    @search_posts = Post.where(genre: params[:word_for_search])

  end

  def keyword_search
     @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @posts = Post.looks(params[:search], params[:word])
    end

    render "search"

  end




  def index
    @posts=Post.all
    @user=current_user
    @post=Post.new
    @users=User.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def update
    @post = Post.find(params[:id])
    @user = current_user
    if @post.update(post_params)
      flash[:notice] ="You have updated post successfully."
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

   private

    def post_params
      params.require(:post).permit(:title,:body,:genre_id,:image,:draft,:user_id,:name)
    end


end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/edit.html.erb
<body>
  <main>
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h1>Editing Post</h1>
           <% if @post.errors.any? %>
             <h3><%= @poat.errors.count %>errors prohibited this obj from being saved:</h3>
             <ul>
              <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
           <% end %>
           <%= form_with model: @post do |f| %>
            <div class="form-group">
              <label for="inputTitle">Title</label>
              <%= f.text_field :title, autofocus: true, class:"form-control", id:"inputTitle"%>
            </div>
            <div class="form-group">
              <label for="inputOpinion">Opinion</label>
              <%= f.text_area :body, autofocus: true, class:"form-control", id:"inputOpinion"%>
            </div>
            <div class="row mt-4">
             <div class="form-inline mx-auto">
              <% if @post.draft == true %>
               <%= f.submit "LIFEHACKを公開", :name => 'publicize_draft', class:'mr-5 btn btn-sm btn-warning' %>
               <%= f.submit "下書きを更新", :name => 'update_draft', class:'mr-5 btn btn-sm btn-outline-secondary' %>
              <% else %>
               <%= f.submit "投稿を更新", :name => 'update_post', class:'btn btn-sm btn-warning text-light' %>
              <% end %>
             </div>
            </div>
            <div class="mt-4 pb-3 text-center">
             <u><%= link_to "投稿を削除", admin_post_path(@post), method: :delete, data: {confirm: "この投稿を削除しますか？"}, class:'text-danger' %></u>
            </div>
           <% end %>
           <%= link_to "投稿一覧", posts_path %>
            |
           <%= link_to "Back", post_path(@post)%>
        </div>
      </div>
    </div>
  </main>
</body>

app/views/admin/posts/index.html.erb
<body>
  <main>
    <% if @post.errors.any? %>
     <%= @post.errors.count %>errors prohibited this obj from being saved:
      <ul>
       <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
       <% end %>
      </ul>
    <% end %>
    <div class="container px-5 px-sm-0">
     <div class="row">


     <div class="col-md-8 offset-md-1">
      <h2>Posts</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>投稿者</th>
            <th>Title</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
           <% @posts.each do |post| %>
          <tr>
            <td>
            <%= link_to admin_user_path(post.user) do %>
             <%= image_tag post.user.get_profile_image(80,80) %>
             <%= post.user.user_name %>
            <% end %>
            </td>
            <td>
            <%= link_to admin_post_path(post) do %>
             <%= post.title %>
            <% end %>
            </td>
           </tr>
         <% end %>
        </tbody>
      </table>
     </div>
     </div>
    </div>
  </main>
</body>

app/views/admin/posts/show.html.erb
<div>
  <%= image_tag @post.image, size:"120x120" %>
  <p>タイトル：<%= @post.title %></p>
  <p>Life Hack：<%= @post.body %></p>
  <p>投稿ユーザー画像：<%= image_tag @post.user.get_profile_image(80,80) %></p>
  <p>ユーザーネーム：<%= @post.user.user_name %></p>
  <p>投稿日：<%= @post.created_at.strftime('%Y/%m/%d') %></p>

    <%= link_to "削除", post_path(@post), method: :delete, class: "btn btn-sm btn-danger" %>
    <%= link_to "編集", edit_admin_post_path(@post),class: "btn btn-sm btn-success" %>
<% if @post.liked_by?(@user) %>
    <p>
      <%= link_to post_likes_path(post_id: @post.id), method: :delete do %>
        ♥<%= @post.likes.count %> いいね
      <% end %>
    </p>
<% else %>
    <p>
      <%= link_to post_likes_path(post_id: @post.id), method: :post do %>
        ♡<%= @post.likes.count %> いいね
      <% end %>
    </p>
<% end %>
</div>

<div>
  <p>コメント件数：<%= @post.comments.count %></p>
  <% @post.comments.each do |comment| %>
    <p><%= image_tag comment.user.get_profile_image(100,100) %></p>
    <%= comment.user.user_name %>
    <%= comment.created_at.strftime('%Y/%m/%d') %><%= comment.body %>

      <%= link_to "削除", post_comment_path(comment.post, comment), method: :delete %>

  <% end %>
</div>
<div>
  <%= form_with model: [@post, @comment] do |f| %>
    <%= f.text_area :body, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>