config/routes.rb
Rails.application.routes.draw do

 devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
  get "/" => "homes#top"
  resources :genres, only: [:index, :edit, :create, :update]
  get "/search" => "posts#search"
  get "/users/unsubscribe" => "users#unsubscribe"
  patch "/users/is_deleted" => "users#is_deleted"
  resources :posts, only: [:index, :create, :new, :show, :edit, :update]
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
    get :likes

  end

  end


 end

scope module: :public do
  root "homes#top"
  get "/about" => "homes#about"
  get "/users/unsubscribe" => "users#unsubscribe"
  patch "/users/is_deleted" => "users#is_deleted"
  resources :users,only: [:index, :create, :new, :show, :edit, :update, :destroy] do
    member do
    get :likes
   end
  end
  resources :posts,only: [:new,:create,:index,:show,:destroy,:edit,:update] do
   resource :likes, only: [:create, :destroy]
   resources :comments, only: [:create, :destroy]
   get 'search'
   end
  get 'keyword_search' => "posts#keyword_search"
  get "/search" => "posts#search"

 end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :user_name, length: { minimum: 2, maximum: 20}
  validates :user_name, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("user_name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("user_name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("user_name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("user_name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def get_profile_image(width, height)
   unless profile_image.attached?
     file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
     profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
   profile_image.variant(resize_to_limit: [width, height]).processed
  end



end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController


  before_action :set_user, only: [:likes]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @post=Post.new

  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] ="You have updated user successfully."
      redirect_to admin_user_path(@user.id)
    else
      render :edit
    end
  end

  def edit
     @user=User.find(params[:id])
     @users=@user.posts
     render :edit
  end

  def index
    @user=User.page(params[:page]).per(10)
    @post=Post.new
    @users=User.all

  end

  def is_deleted
    @user = User.find(params[:id])
    # @user.is_deleted = true
    if @user.update(is_deleted: true)
      reset_session
      redirect_to admin_users_path
    end
  end

  def unsubscribe
  end

  def likes
    likes = Like.where(user_id: @user.id).pluck(:post_id)
    @like_posts = Post.find(likes)
  end


  private

  def user_params
    params.require(:user).permit(:user_name, :introduction, :profile_image)
  end

  def set_user
    @user = User.find(params[:id])
  end


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<body>
  <main>
   <div class="container">
    <div class="row">
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <h2>User Info</h2>
         <% if @user.errors.any? %>
             <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
             <ul>
              <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
         <% end %>
         <%= form_with model: @user do |f| %>
          <div class="form-group">
           <label for="inputName">Name</label>
           <%= f.text_field :user_name, autofocus: true, class:"form-control", id:"inputName"%>
          </div>
          <div class="form-group">
           <label for="inputImage">Image</label>
           <%= f.file_field :profile_image, class:"form-control-file user_image", placeholder: "プロフィール画像", accept: "image/*" %>
          </div>
          <div class="form-group">
            <label for="inputIntroducion">Introduction</label>
            <%= f.text_area :introduction, autofocus: true, class:"form-control", id:"inputIntroduction"%>
          </div>
          <div class="form-group">
           <%= f.submit "更新する", class:"btn btn-success" %>
          </div>

          <div class="form-group">
            <%= link_to "退会", admin_users_unsubscribe_path(id: @user.id), class: "btn btn-danger" %>

          </div>

         <% end %>
     </div>
    </div>
   </div>
  </main>
</body>

app/views/admin/users/index.html.erb
<body>
  <main>
   <p id="notice"></p>
   <div class="container px-5 px-sm-0">
    <div class="row">



    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Profile Image</th>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
         <% @users.each do |user| %>
          <% if user.is_deleted == false %>
          <tr>
            <td><%= image_tag user.get_profile_image(80,80) %></td>
            <td><%= user.user_name %></td>
            <td><%= link_to "詳細", admin_user_path(user.id) %></td>
             <td><%= user.user_name %></td>
          </tr>
         <%end%>
         <% end %>
        </tbody>
      </table>
     </div>
    </div>
   </div>

app/views/admin/users/likes.html.erb
<div class="col-md-8 offset-md-1">
<h1>いいねした投稿一覧</h1>
<%#= render 'posts/post', like_post: @like_posts %>
<% @like_posts.each do |post| %>
<%= link_to image_tag( post.image.variant(resize: '100x100') ), admin_post_path(post.id) %>
<%= link_to post.user.user_name, admin_user_path(post.user.id) %>
<i class="fa fa-heart unlike-btn"></i>
<%= post.likes.length %>
<%= link_to post.title, admin_post_path(post.id) %>
<% end %>
</div>

app/views/admin/users/show.html.erb
<body>
 <main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
   <div class="row">

               <div class="col-md-3">
          <h2>User Info</h2>
          <%= image_tag @user.get_profile_image(100,100) %>
          <%= link_to "いいねした投稿", likes_user_path(@user) %>
          <table class="table">
            <tbody>
              <tr>
                <th>User name</th>
                <th><%= @user.user_name %></th>
              </tr>
              <tr>
               <th>Introduction</th>
               <th><%= @user.introduction %></th>
              </tr>
            </tbody>
          </table>
          <div class="row">
            <%= link_to edit_admin_user_path(@user.id),class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
            <%end%>
          </div>
            <li class="mt-3">
             <%= form_with url: search_path, method: :get, local: true do |f| %>
               <%= f.collection_select :word_for_search, Genre.all, :id, :name %>
                  <%= f.submit "検索" %>
               <% end %>
             <div class="search_form">
              <%= form_with url: keyword_search_path, local: true, method: :get do |f| %>
               <%= f.text_field :word %>
               <%= f.select :range, options_for_select([['User'], ['Post']]) %>
               <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
              <%= f.submit "検索", class: "btn btn-primary" %>
              <% end %>
            </div>
            </li>
         </div>


    <div class="col-md-8 offset-md-1">
      <h2>投稿一覧</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>タイトル</th>
            <th>ジャンル</th>
            <th colspan="3"></th>
          </tr>
        </thead>
         <tbody>
           <% @posts.each do |post| %>
          <tr>
            <td>
             <%= image_tag post.user.get_profile_image(80,80) %>
             <%= post.user.user_name %>
            </td>
            <td>
            <%= link_to admin_post_path(post) do %>
             <%= post.title %>
            <% end %>
            </td>
             <td><%= post.genre.name %></td>
           <% end %>
          </tr>
        </tbody>
      </table>
    </div>
   </div>
  </div>
 </main>
</body>

app/views/admin/users/unsubscribe.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2>退会画面</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-4 mb-4 offset-md-1">
      <h4>退会しますか？</h4>
    </div>
  </div>
  <div class="row offset-md-2">
    <div class="col-3 mb-4">
      <%= link_to "退会しない", admin_users_path, class:"btn btn-success" %>
    </div>
    <div class="col-3 mb-4">
      <%= link_to "退会する", admin_users_is_deleted_path(id: params[:id]), class:"btn btn-danger", method: :patch, data: { confirm: "本当に退会しますか？" } %>
    </div>
  </div>
</div>