config/routes.rb
Rails.application.routes.draw do

 devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
  get "/" => "homes#top"
  resources :genres, only: [:index, :edit, :create, :update]
  get "/search" => "posts#search"
  get "/users/unsubscribe" => "users#unsubscribe"
  patch "/users/is_deleted" => "users#is_deleted"
  resources :posts, only: [:index, :create, :new, :show, :edit, :update]
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
    get :likes

  end

  end


 end

scope module: :public do
  root "homes#top"
  get "/about" => "homes#about"
  get "/users/unsubscribe" => "users#unsubscribe"
  patch "/users/is_deleted" => "users#is_deleted"
  resources :users,only: [:index, :create, :new, :show, :edit, :update, :destroy] do
    member do
    get :likes
   end
  end
  resources :posts,only: [:new,:create,:index,:show,:destroy,:edit,:update] do
   resource :likes, only: [:create, :destroy]
   resources :comments, only: [:create, :destroy]
   get 'search'
   end
  get 'keyword_search' => "posts#keyword_search"
  get "/search" => "posts#search"

 end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book_mark.rb
class BookMark < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/customer.rb
class Customer < ApplicationRecord
  
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post


end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

with_options presence: true, on: :publicize do
  validates :title
  validates :body
  validates :genre_id

end
validates :title, length: { maximum: 30 }, on: :publicize
validates :body, length: { maximum: 500 }, on: :publicize


  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @post = Post.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

  def get_image(width, height)
   unless image.attached?
     file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
     image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :user_name, length: { minimum: 2, maximum: 20}
  validates :user_name, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("user_name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("user_name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("user_name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("user_name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def get_profile_image(width, height)
   unless profile_image.attached?
     file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
     profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
   profile_image.variant(resize_to_limit: [width, height]).processed
  end



end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/likes_controller.rb
class Admin::LikesController < ApplicationController

  def create
    post = Post.find(params[:post_id])
    like = user.likes.new(post_id: post.id)
    like.save
    redirect_to admin_post_path(post)
  end

  def destroy
    post = Post.find(params[:post_id])
    like = user.likes.find_by(post_id: post.id)
    like.destroy
    redirect_to admin_post_path(post)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    if resource == :admin
      admin_user_path
    else
      root_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      new_user_session_path
    end
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
  end
end

app/helpers/admin/book_marks_helper.rb
module Admin::BookMarksHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/likes_helper.rb
module Admin::LikesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<section id="footer">
  <div class="container">
    <div class="row text-center text-xs-center text-sm-left text-md-left ">
      <div class="col-xs-12 col-sm-8 col-md-6">

        <div class="row">
          <div class="col-6">
      <ul class="list-unstyled quick-links">
			  <li><i class="fa fa-angle-double-right"></i><%= link_to "TOP", root_path %></li>
			  <li><i class="fa fa-angle-double-right"></i><%= link_to "会員様一覧", users_path %></li>
			  <li><i class="fa fa-angle-double-right"></i><%= link_to "投稿一覧", posts_path %></li>
			</ul>

  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LIFE HACKERS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/17908fdbcd.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
   <header>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
       <div class="container">
         <a class="navbar-brand" href="https://ea11e21ad98847218d40a96605fee3e7.vfs.cloud9.ap-northeast-1.amazonaws.com/">
           <span>LIFE HACKERS</span>
         </a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle-navigation">
           <span class="navabr-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNavDropdown">
           <ul class="navbar-nav ml-auto">
             <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to admin_posts_path do %>
                  <i class="fas fa-book-open">投稿一覧</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_users_path do %>
                  <i class="fas fa-users">会員一覧</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_genres_path do%>
                  <i class="fa-solid fa-tag">ジャンル一覧</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_admin_session_path, method: :delete do %>
                  <i class="fas fa-sign-out-alt">ログアウト</i>
                <% end %>
              </li>

             <% elsif user_signed_in? %>
             <li>
              <%=link_to user_path(current_user),class: "nav-link text-light" do %>
               <i class="fa-solid fa-user"></i>
               マイページ
              <% end %>
             </li>
             <li>
              <%=link_to new_post_path,class: "nav-link text-light" do %>
              <i class="fa-solid fa-pen-clip"></i>
              投稿フォーム
              <% end %>
             <li>
              <%=link_to users_path,class: "nav-link text-light" do %>
              <i class="fas fa-users"></i>
              会員一覧
              <% end %>
             </li>
              <li>
              <%=link_to posts_path,class: "nav-link text-light" do %>
              <i class="fas fa-book-open"></i>
              投稿一覧
              <% end %>
             </li>
              <li>

             <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
              <i class="fas fa-sign-out-alt"></i>
              ログアウト
              <% end %>
             </li>

             <% else %>
             <li>
              <%=link_to root_path,class: "nav-link text-light" do %>
              <i class="fas fa-home"></i>
              トップページ
              <% end %>
             </li>
             <li>
              <%=link_to about_path,class: "nav-link text-light" do %>
              <i class="fas fa-link"></i>
              サイト概要
              <% end %>
             </li>
             <li>
              <%=link_to new_user_registration_path,class: "nav-link text-light" do %>
              <i class="fas fa-user-plus"></i>
              新規登録
              <% end %>
             </li>
             <li>
              <%=link_to new_user_session_path,class: "nav-link text-light" do %>
              <i class="fas fa-sign-in-alt"></i>
              ログイン
              <% end %>
             </li>
             <% end %>
           </ul>
         </div>
       </div>
     </nav>
   </header>
   <%= render 'public/shared/flash_message' %>
      <%= yield %>
   <footer>
    <div class="container mt-5">
     <div class="row">
       <div>
        <ul class="list-unstyled quick-links" "text-left">
			  <li><i class="fa fa-angle-double-right"></i><%= link_to "TOP", root_path %></li>
			  <li><i class="fa fa-angle-double-right"></i><%= link_to "会員様一覧", users_path %></li>
			  <li><i class="fa fa-angle-double-right"></i><%= link_to "投稿一覧", posts_path %></li>
			</ul>

       </div>
     </div>
    </div>
    <div>
      <p class= "col text-center">CopyRight Infratop.inc</p>
    </div>
   </footer>
  </body>
</html>